name: Docker Image CI

on: [push]

jobs:   

  build:
    name: Build
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
      env:
        IMAGE_NAME: mmornati/docker-ghostblog
    - name: Checkout Official Images
      run: git clone https://github.com/docker-library/official-images.git official-images
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mmornati/docker-ghostblog
    - name: Start New Docker
      run: docker run -d --name blogtest -p 2368:2368 -e WEB_URL=http://localhost:2368 -e NODE_ENV=production mmornati/docker-ghostblog
    - name: Wait for container startup
      run: until $(curl --output /dev/null --silent --head --fail http://localhost:2368); do
            echo "waiting for ghostblog container...";
            sleep 10;
           done
    - name: Test with Official Images
      run: official-images/test/run.sh "mmornati/docker-ghostblog"
    - name: Test Started Blog
      run: curl http://localhost:2368 | grep "The professional publishing platform"
      
